name: "upstream_prod"
version: "0.9.5"
config-version: 2

require-dbt-version: [">=1.5.0", "<3.0.0"]

macro-paths: ["macros"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
