name: 'import_project'
version: '1.0.0'
config-version: 2

profile: 'upstream_prod_db'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  import_project:
    marts:
      +schema: marts
    staging:
      +schema: stg

snapshots:
  import_project:
    target_schema: snapshots
    unique_key: id
    strategy: timestamp
    updated_at: updated_at
