name: 'upstream_prod_integration_tests'
version: '1.0.0'
config-version: 2

profile: 'upstream_prod_db'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  upstream_prod_integration_tests:
    marts:
      +schema: marts
    staging:
      +schema: stg

snapshots:
  upstream_prod_integration_tests:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at
vars:
  upstream_prod_database: upstream__prod_db
  upstream_prod_fallback: true
  upstream_prod_prefer_recent: true

flags:
  require_generic_test_arguments_property: true